SELECT  
    CAST(AVG(tmin)               AS NUMERIC(17,2)) AS tmin,
    CAST(AVG(tmed)               AS NUMERIC(17,2)) AS tmed,
    CAST(AVG(tmax)               AS NUMERIC(17,2)) AS tmax,
    CAST(AVG(umidade)            AS NUMERIC(17,2)) AS umidade,
    CAST(AVG(velocidadevento)    AS NUMERIC(17,2)) AS velocidadevento,
    CAST(SUM(radiacaosolar)      AS NUMERIC(17,2)) AS radiacaosolar,
    CAST(SUM(chuva)              AS NUMERIC(17,2)) AS chuva,
    CAST(STDDEV(tmin)            AS NUMERIC(17,2)) AS dptmin,
    CAST(STDDEV(tmed)            AS NUMERIC(17,2)) AS dptmed,
    CAST(STDDEV(tmax)            AS NUMERIC(17,2)) AS dptmax,
    CAST(STDDEV(umidade)         AS NUMERIC(17,2)) AS dpumidade,
    CAST(STDDEV(velocidadevento) AS NUMERIC(17,2)) AS dpvelocidadevento,
    CAST(STDDEV(radiacaosolar)   AS NUMERIC(17,2)) AS dpradiacaosolar,
    CAST(STDDEV(chuva)           AS NUMERIC(17,2)) AS dpchuva,
    CAST(VARIANCE(tmin)          AS NUMERIC(17,2)) AS vartmin,
    CAST(VARIANCE(tmed)          AS NUMERIC(17,2)) AS vartmed,
    CAST(VARIANCE(tmax)          AS NUMERIC(17,2)) AS vartmax,
    CAST(VARIANCE(umidade)       AS NUMERIC(17,2)) AS varumidade,
    CAST(VARIANCE(velocidadevento) AS NUMERIC(17,2)) AS varvelocidadevento,
    CAST(VARIANCE(radiacaosolar) AS NUMERIC(17,2)) AS varradiacaosolar,
    CAST(VARIANCE(chuva)         AS NUMERIC(17,2)) AS varchuva,
    CAST(SUM(somatermica)        AS NUMERIC(17,2)) AS somatermica,
    CAST(STDDEV(somatermica)     AS NUMERIC(17,2)) AS dpsomatermica,
    CAST(VARIANCE(somatermica)   AS NUMERIC(17,2)) AS varsomatermica,
    CAST(SUM(def)                AS NUMERIC(17,2)) AS def,
    CAST(STDDEV(def)             AS NUMERIC(17,2)) AS dpdef,
    CAST(VARIANCE(def)           AS NUMERIC(17,2)) AS vardef,
    CAST(SUM(exc)                AS NUMERIC(17,2)) AS exc,
    CAST(STDDEV(exc)             AS NUMERIC(17,2)) AS dpexc,
    CAST(VARIANCE(exc)           AS NUMERIC(17,2)) AS varexc
FROM clima_evapo
WHERE data BETWEEN %s AND %s
